flask_app/main/routes.py
from flask import render_template, request, current_app, Blueprint, redirect, url_for

import json
from flask_app.models import Post, User

main = Blueprint("main", __name__)


@main.route("/")
def index():
    posts = Post.query.all()[::-1]
    return render_template("index.html", title="Home", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title="About")


@main.route("/user/<username>")
def user_detail(username):
    user = User.query.filter_by(username=username).first()

    return render_template(
        "user_detail.html",
        user=user,
        posts=user.posts[::-1],
        comments=user.comments[::-1],
    )


@main.route("/csp_error_handling", methods=["POST"])
def report_handler():
    """
    Receives POST requests from the browser whenever the Content-Security-Policy 
    is violated. Processes the data and logs an easy-to-read version of the message
    in your console.
    """
    report = json.loads(request.data.decode())["csp-report"]

    # current_app.logger.info(json.dumps(report, indent=2))

    violation_desc = "\nViolated directive: %s, \nBlocked: %s, \nOriginal policy: %s \n" % (
        report["violated-directive"],
        report["blocked-uri"],
        report["original-policy"]
    )

    current_app.logger.info(violation_desc)
    return redirect(url_for("main.index"))

flask_app/posts/routes.py
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint,
    session,
    current_app,
)
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, Post, Comment
from flask_app.posts.forms import PostTypeForm, CreatePostForm, CommentForm


posts = Blueprint("posts", __name__)


@posts.route("/create_post", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostTypeForm()

    if form.validate_on_submit():
        post_type = form.post_type.data
        session["post_type"] = post_type

        return redirect(url_for("posts.create_post_detail"))

    return render_template(
        "create_post_prelim.html", title="Create Post - Preliminary", form=form
    )


@posts.route("/create_post_detail", methods=["GET", "POST"])
@login_required
def create_post_detail():
    form = CreatePostForm()

    post_type = session["post_type"]
    is_video = True if post_type == "video" else False

    if form.validate_on_submit():

        if is_video:
            content = form.video_id.data
        else:
            content = form.text.data

        post = Post(
            title=form.title.data,
            is_video=is_video,
            content=content,
            author=current_user,
        )

        db.session.add(post)
        db.session.commit()

        return redirect(url_for("main.index"))

    return render_template(
        "create_post.html", title="Create Post", is_video=is_video, form=form
    )


@posts.route("/posts/<title>", methods=["GET", "POST"])
def post_detail(title):
    form = CommentForm()

    post = Post.query.filter_by(title=title).first()

    if form.validate_on_submit():
        comment = Comment(content=form.text.data, author=current_user, post=post)

        db.session.add(comment)
        db.session.commit()

        return redirect(request.path)

    comments = post.comments[::-1]

    return render_template("post_detail.html", post=post, comments=comments, form=form)

flask_app/users/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, Post
from flask_app.users.forms import RegistrationForm, LoginForm, UpdateForm


users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = RegistrationForm()

    if form.validate_on_submit():
        #user = User.query.filter_by(username=form.username.data).first()
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(username=form.username.data, email=form.email.data, password=hashed)
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('users.login'))
    
    return render_template('register.html', title='Register', form=form)
   # return 'Register'

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('users.account'))

    return render_template('login.html', title='Login', form=form)

    #return 'Login'


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateForm()

    if form.validate_on_submit():
        current_user.username = form.username.data

        db.session.commit()

        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
    
    return render_template('account.html', title='Account', form=form)
    #return 'Account'

flask_app/templates/about.html
{% extends "base.html" %}
{% block content %}
<h2>About</h2>
<p class="green-text">This is project 4. This is a very basic example of creating a social news/media site like Reddit. Users can register,
    login, look at account details,
    create either a video <b>or</b> a text post, and comment on other people's posts.
    </canvas></p>
{% endblock %}

flask_app/templates/account.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>{{ current_user.username }}</h2>
    <p>{{ current_user.email }}</p>
</div>
<div>
    <form action="" method="post">
        
        {{ form.csrf_token }}
            <div>
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit }}
            </div>
    </form>
</div>
<a href={{ url_for('main.user_detail', username=current_user.username) }}>
    <h4>Click here to see all of your posts and comments!</h4>
</a>
{% endblock %}

flask_app/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href={{ url_for('static', filename='css/custom.css') }}>

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Flask App</title>
    {% endif %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">

            <a class="navbar-brand" href={{ url_for('main.index' )}}>Flask App</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href={{ url_for('main.index') }} class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('main.about') }} class="nav-link">About</a>
                    </li>
                </ul>

                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href=# class="nav-link">Logged in as: <b>{{ current_user.username }}</b></a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('posts.create_post') }} class="nav-link">Create a Post!</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.account' )}} class="nav-link">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.logout' )}} class="nav-link">Logout</a>
                    </li>
                </ul>

                {% else %}

                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('users.login' )}} class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.register' )}} class="nav-link">Register</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

flask_app/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Create Post! - Part 2</h2>
    <p>Here you'll choose a title and input text or a YouTube video ID</p>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.title.label(class="form-control-label") }}
            {{ form.title(class="form-control form-control-md") }}

            {% if form.title.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

        </div>
        <div>
            {% if is_video %}
            {{ form.video_id.label(class="form-control-label") }}

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon3">https://youtu.be/</span>
                </div>
                {{ form.video_id(class="form-control", aria_describedby="basic-addon3") }}

                {% if form.video_id.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.video_id.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
                {% else %}

                {{ form.text.label(class="form-control-label") }}
                {{ form.text(class="form-control form-control-md", rows=10) }}

                {% endif %}
            </div>
            <div>
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
    </form>
</div>
{% endblock %}

flask_app/templates/create_post_prelim.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Create Post! - Part 1</h2>
    <p>Here you'll pick the type of post you want to create, and then proceed to step 2 of submitting a post!</p>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.post_type.label(class="form-control-label") }}
            {# {{ form.username(class="form-control form-control-md") }} #}

            {{ form.post_type() }}

            {% if form.post_type.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.post_type.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>

            {% endif %}
        </div>
        <div>
            {{ form.submit(class="form-control form-control-lg") }}
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "base.html" %}
{% block content %}
<div>
    <h1>Posts</h1>
</div>

<div class="list-group">
    {% for post in posts %}
    <div class="list-group-item">
        <div class="d-flex w-100 justify-content-between">
            <a href={{ url_for('posts.post_detail', title=post.title) }}>
                <h5 class="mb-1">{{ post.title }}</h5>
            </a>
            <small class="text-muted"><a href={{ url_for('posts.post_detail', title=post.title) }}>Comments</a> • <a
                    href={{ url_for('main.user_detail', username=post.author.username) }}>{{ post.author.username }}</a>
                • {{ post.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
        </div>
        {% if post.is_video %}
        <div class="embed-responsive embed-responsive-16by9">
            <iframe src={{ "https://www.youtube.com/embed/%s" % post.content }}
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
            </iframe>
        </div>
        {% else %}
        {% if post.content|length >= 400 %}
        <p class="mb-1">{{ post.content[:400] }}...</p>
        {% else %}
        <p class="mb-1">{{ post.content }}</p>
        {% endif %}
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Log In</h2>
</div>
<div>
    If you <b>don't</b> have an account, then <a href={{ url_for('users.register') }}>Register!</a>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.username.label(class="form-control-label green-text") }}
            {{ form.username(class="form-control form-control-md") }}

            {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg") }}
        </div>
        <div>
            {{ form.submit(class="form-control form-control-lg") }}
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/post_detail.html
{% extends "base.html" %}
{% block content %}
<article class="content-section">
    <div>
        <h3>{{ post.title }}</h3>

        {% if post.is_video %}

        <iframe width="560" height="315" src={{ "https://www.youtube.com/embed/%s" % post.content }} frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
        </iframe>

        {% else %}

        <p>{{ post.content }}</p>

        {% endif %}

        <div>
            <p>
                <a href={{ url_for('main.user_detail', username=post.author.username) }}>
                    {{ post.author.username -}}
                </a> •
                {{ post.date.strftime('%b %d, %Y at %I:%M %p') }}
            </p>
        </div>
    </div>
</article>
<h3>Comments:</h3>
{% if comments %}
<div class="list-group">
    {% for comment in comments %}
    <div class="list-group-item">
        <div class="d-flex w-100 justify-content-between">
            <a href={{ url_for('main.user_detail', username=comment.author.username) }}>
                <h5 class="mb-1">{{ comment.author.username }}</h5>
            </a>
            <small class="text-muted">{{ comment.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
        </div>
        <p class="mb-1">{{ comment.content }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<h5>No comments yet... be the first! (Make sure you're logged in)</h5>
{% endif %}

{% if current_user.is_authenticated %}
<div>
    <h4>Submit a new comment!</h4>
    <form action="" method="post">
        
        {{ form.csrf_token }}
        <div>
            {{ form.text.label(class="form-control-label") }}
            {{ form.text(class="form-control form-control-md", rows=10) }}

            {% if form.text.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.text.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>

        <div>
            {{ form.submit(class="form-control form-control-lg") }}
        </div>
    </form>
</div>
{% endif %}

{% endblock %}

flask_app/templates/register.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Registration</h2>
</div>
<div>
    If you already have an account, then just <a href={{ url_for('users.login') }}>Log In!</a>
</div>
<!-- Registration Form: -->
<div>
    <form action="" method="post">
        
        {{ form.csrf_token }}
            <div>
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
    </form>
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>{{ user.username }}'s History</h2>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3>Posts:</h3>
            <div class="list-group">
                {% for post in posts %}
                <div class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <a href={{ url_for('posts.post_detail', title=post.title) }}>
                            <h5 class="mb-1">{{ post.title }}</h5>
                        </a>
                        <small class="text-muted"><a
                                href={{ url_for('posts.post_detail', title=post.title) }}>Comments</a>
                            • <a
                                href={{ url_for('main.user_detail', username=current_user.username) }}>{{ post.author.username }}</a>
                            • {{ post.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
                    </div>
                    {% if post.is_video %}
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe src={{ "https://www.youtube.com/embed/%s" % post.content }}
                            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen>
                        </iframe>
                    </div>
                    {% else %}
                    {% if post.content|length >= 400 %}
                    <p class="mb-1">{{ post.content[:400] }}...</p>
                    {% else %}
                    <p class="mb-1">{{ post.content }}</p>
                    {% endif %}
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-4">
            <h3>Comments:</h3>
            <div class="list-group">
                {% for comment in comments %}
                <div class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">On <a
                                href={{ url_for('posts.post_detail', title=comment.post.title) }}>{{ comment.post.title }}</a>
                        </h5>
                        <small class="text-muted">{{ comment.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
                    </div>
                    <p class="mb-1">{{ comment.content }}</p>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
{% endblock %}